### ISSUE TITLE
More methods

### ISSUE THREAD

**Issue by jonaaix** [nitro404/change-case-bundled#1]
Great to find this project. I was just doing the same thing right now.
However there seems to be some more methods available:
```
isLowerCase
isUpperCase
```
Would be nice to have them added for completeness.

**Comment by nitro404** [comment]
Hi @btxtiger! Thanks for raising this issue. I had originally stripped those methods because I was primarily using this module to change cases, but I definitely agree that they should be added. I'll see about hooking those in now. Sorry for the delay in following up on this, GitHub notifications don't seem to notify me of new issues.

**Comment by nitro404** [comment]
This is now implemented in v1.1.3, please feel to upgrade to this release at your earliest convenience!
